from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_remote(object):
    def setupUi(self, remote):
        remote.setObjectName("remote")
        remote.resize(160, 325)
        remote.setMinimumSize(QtCore.QSize(160, 325))
        remote.setMaximumSize(QtCore.QSize(160, 325))
        remote.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(parent=remote)
        self.centralwidget.setObjectName("centralwidget")
        self.button_vol_up = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_vol_up.setGeometry(QtCore.QRect(0, 90, 50, 50))
        self.button_vol_up.setObjectName("button_vol_up")
        self.button_vol_down = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_vol_down.setGeometry(QtCore.QRect(0, 160, 50, 50))
        self.button_vol_down.setObjectName("button_vol_down")
        self.button_channel_up = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_channel_up.setGeometry(QtCore.QRect(110, 90, 50, 50))
        self.button_channel_up.setObjectName("button_channel_up")
        self.button_channel_down = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_channel_down.setGeometry(QtCore.QRect(110, 160, 50, 50))
        self.button_channel_down.setObjectName("button_channel_down")
        self.button_power = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_power.setGeometry(QtCore.QRect(0, 10, 50, 50))
        self.button_power.setObjectName("button_power")
        self.button_mute = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_mute.setGeometry(QtCore.QRect(0, 210, 80, 35))
        self.button_mute.setObjectName("button_mute")
        self.button_recall = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_recall.setGeometry(QtCore.QRect(80, 210, 80, 35))
        self.button_recall.setObjectName("button_recall")
        self.label_volume = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_volume.setGeometry(QtCore.QRect(0, 140, 50, 16))
        self.label_volume.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_volume.setObjectName("label_volume")
        self.label_channel = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_channel.setGeometry(QtCore.QRect(110, 140, 50, 16))
        self.label_channel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_channel.setObjectName("label_channel")
        self.label_curr_vol = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_curr_vol.setGeometry(QtCore.QRect(10, 70, 30, 20))
        self.label_curr_vol.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_curr_vol.setObjectName("label_curr_vol")
        self.label_curr_chan = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_curr_chan.setGeometry(QtCore.QRect(120, 70, 30, 20))
        self.label_curr_chan.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_curr_chan.setObjectName("label_curr_chan")
        self.button_power_indicator = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.button_power_indicator.setGeometry(QtCore.QRect(50, 20, 20, 20))
        self.button_power_indicator.setText("")
        self.button_power_indicator.setCheckable(True)
        self.button_power_indicator.setObjectName("button_power_indicator")
        remote.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=remote)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 160, 33))
        self.menubar.setObjectName("menubar")
        remote.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=remote)
        self.statusbar.setObjectName("statusbar")
        remote.setStatusBar(self.statusbar)

        self.retranslateUi(remote)
        QtCore.QMetaObject.connectSlotsByName(remote)

    def retranslateUi(self, remote):
        _translate = QtCore.QCoreApplication.translate
        remote.setWindowTitle(_translate("remote", "Remote"))
        self.button_vol_up.setText(_translate("remote", "+"))
        self.button_vol_down.setText(_translate("remote", "-"))
        self.button_channel_up.setText(_translate("remote", "^"))
        self.button_channel_down.setText(_translate("remote", "^"))
        self.button_power.setText(_translate("remote", "O/I"))
        self.button_mute.setText(_translate("remote", "MUTE"))
        self.button_recall.setText(_translate("remote", "RECALL"))
        self.label_volume.setText(_translate("remote", "VOL"))
        self.label_channel.setText(_translate("remote", "CH"))
        self.label_curr_vol.setText(_translate("remote", "0"))
        self.label_curr_chan.setText(_translate("remote", "0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    remote = QtWidgets.QMainWindow()
    ui = Ui_remote()
    ui.setupUi(remote)
    remote.show()
    sys.exit(app.exec())
